apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  generation: 5
  labels:
    app: gloo
  name: default
  namespace: gloo-system
spec:
  discovery:
    fdsMode: WHITELIST
  discoveryNamespace: gloo-system
  gateway:
    readGatewaysFromAllNamespaces: false
    validation:
      allowWarnings: true
      alwaysAccept: true
      proxyValidationServerAddr: gloo:9988
  gloo:
    disableKubernetesDestinations: false
    disableProxyGarbageCollection: false
    enableRestEds: false
    restXdsBindAddr: 0.0.0.0:9976
    xdsBindAddr: 0.0.0.0:9977
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  ratelimit:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 2
        unit: MINUTE
      value: per-minute
  ratelimitServer:
    ratelimitServerRef:
      name: default-task-service-8080
      namespace: gloo-system
  refreshRate: 60s